# Generated by Django 5.1 on 2026-03-02 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QADocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.CharField(db_index=True, max_length=500, unique=True)),
                ('s3_download_url', models.URLField(max_length=2000)),
                ('document_filename', models.CharField(default='document', max_length=500)),
                ('file_type', models.CharField(default='', max_length=20)),
                ('full_text', models.TextField()),
                ('char_count', models.IntegerField(default=0)),
                ('char_page_map', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qa_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QASession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qa_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='qa_sessions_user_id_00b235_idx')],
            },
        ),
        migrations.CreateModel(
            name='QAInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answers_per_document', models.JSONField(default=list)),
                ('asked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='qa.qasession')),
            ],
            options={
                'db_table': 'qa_interactions',
                'ordering': ['asked_at'],
            },
        ),
        migrations.CreateModel(
            name='QASessionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_links', to='qa.qadocument')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_documents', to='qa.qasession')),
            ],
            options={
                'db_table': 'qa_session_documents',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['session', 'position'], name='qa_session__session_72b395_idx')],
                'unique_together': {('session', 'document')},
            },
        ),
    ]
