# Generated by Django 5.1 on 2026-03-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qasession',
            name='name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
