# Generated by Django 5.1 on 2026-03-17 09:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRuleExtractionJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_filename', models.CharField(blank=True, default='', max_length=500)),
                ('full_text', models.TextField(blank=True, default='')),
                ('policy_type', models.CharField(blank=True, default='', max_length=500)),
                ('extracted_rules', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'policy_rule_extraction_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
