# Generated by Django 5.1 on 2026-03-02 05:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXTRACTING', 'Extracting Document'), ('DETECTING_JURISDICTION', 'Detecting Jurisdiction'), ('ANALYZING', 'Analyzing Clauses'), ('GENERATING_REPORTS', 'Generating Reports'), ('COMPLETED', 'Completed'), ('PARTIAL_FAILURE', 'Partial Failure (Resumable)'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=30)),
                ('error_message', models.TextField(blank=True, default='')),
                ('document_url', models.TextField(blank=True, default='')),
                ('document_filename', models.CharField(default='document', max_length=500)),
                ('file_type', models.CharField(blank=True, default='', max_length=20)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('full_text', models.TextField(blank=True, default='')),
                ('agreement_type', models.CharField(blank=True, default='', max_length=500)),
                ('agreement_details', models.JSONField(default=dict)),
                ('parties', models.JSONField(default=dict)),
                ('property_details', models.JSONField(default=dict)),
                ('report_format', models.CharField(default='markdown', max_length=20)),
                ('total_clauses', models.IntegerField(default=0)),
                ('completed_clauses', models.IntegerField(default=0)),
                ('failed_clauses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analysis_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='analysis_jo_status_5eec4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClauseConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clause_a_title', models.CharField(max_length=1000)),
                ('clause_b_title', models.CharField(max_length=1000)),
                ('conflict_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_records', to='analyzer.analysisjob')),
            ],
            options={
                'db_table': 'clause_conflicts',
            },
        ),
        migrations.CreateModel(
            name='JobClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clause_ref_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=1000)),
                ('value', models.TextField()),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('position', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='analyzer.analysisjob')),
            ],
            options={
                'db_table': 'job_clauses',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ClauseResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('MATCH', 'Match'), ('NOT_FOUND', 'Not Found'), ('VIOLATION', 'Violation'), ('PARTIALLY_SATISFIED', 'Partially Satisfied')], db_index=True, max_length=30)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('relevant_text', models.TextField(blank=True, default='')),
                ('ai_added_text', models.TextField(blank=True, default='')),
                ('parties_obligated', models.JSONField(default=list)),
                ('missing_values', models.JSONField(default=list)),
                ('key_dates_durations', models.JSONField(default=list)),
                ('binding_strength', models.CharField(choices=[('MUST/SHALL', 'Must/Shall'), ('SHOULD', 'Should'), ('MAY/CAN', 'May/Can'), ('VAGUE', 'Vague')], default='VAGUE', max_length=20)),
                ('ai_provider_used', models.CharField(blank=True, default='', max_length=50)),
                ('analysis_attempt', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clause', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analyzer.jobclause')),
            ],
            options={
                'db_table': 'clause_results',
            },
        ),
        migrations.CreateModel(
            name='JobJurisdiction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jurisdiction', models.CharField(default='Unknown', max_length=500)),
                ('agreement_type', models.CharField(blank=True, default='', max_length=500)),
                ('applicable_laws', models.JSONField(default=list)),
                ('checklist', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jurisdiction_info', to='analyzer.analysisjob')),
            ],
            options={
                'db_table': 'job_jurisdiction',
            },
        ),
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('PDF_REPORT', 'PDF Report'), ('PDF_SUMMARY', 'PDF Summary'), ('MARKDOWN_REPORT', 'Markdown Report'), ('MARKDOWN_SUMMARY', 'Markdown Summary'), ('DOCX_REPORT', 'DOCX Report'), ('DOCX_SUMMARY', 'DOCX Summary')], max_length=30)),
                ('storage_backend', models.CharField(default='r2', max_length=10)),
                ('file_key', models.CharField(max_length=1000)),
                ('presigned_url', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='analyzer.analysisjob')),
            ],
            options={
                'db_table': 'job_reports',
            },
        ),
        migrations.AddIndex(
            model_name='jobclause',
            index=models.Index(fields=['job', 'status'], name='job_clauses_job_id_c7de75_idx'),
        ),
        migrations.AddIndex(
            model_name='jobclause',
            index=models.Index(fields=['job', 'position'], name='job_clauses_job_id_86b37b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobclause',
            index=models.Index(fields=['job', 'clause_ref_id'], name='job_clauses_job_id_83a0b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobclause',
            unique_together={('job', 'clause_ref_id')},
        ),
        migrations.AddIndex(
            model_name='clauseresult',
            index=models.Index(fields=['result'], name='clause_resu_result_9a89fb_idx'),
        ),
        migrations.AddIndex(
            model_name='jobreport',
            index=models.Index(fields=['job', 'report_type'], name='job_reports_job_id_eb8072_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobreport',
            unique_together={('job', 'report_type')},
        ),
    ]
